version: '2.0'
services:
  asmon:
    build: .
    network_mode: "host"
    volumes:
      - ./:/home/asmon/
    restart: on-failure
    mem_limit: 2048m
    command:
      - 'bash'
      - '-c'
      - 'chown asmon:asmon /home/asmon/ /home/asmon/config.py; su -c "python3 -u asmon.py" asmon'
